### ISSUE TITLE
[question] not in CPAN?

### ISSUE THREAD

**Issue by micwoj92** [Starlink/perl-NDF#1]
Hello, page https://metacpan.org/pod/Astro::FITS::Header::NDF references this (I guess it's right one) module and links to https://metacpan.org/pod/NDF which doesn't exist. Was this never uploaded or deleted for some reason?

**Comment by grahambell** [comment]
Building and installing this module currently requires a copy of the Starlink software collection to be installed.  So without having Starlink present, an automated installation of this module from CPAN would not succeed.  However releases of the Starlink software collection should already include a copy of this module.

**Comment by micwoj92** [comment]
Thanks for answering, makes sense.
